// Station lookup by the name a user types in Garmin Connect settings.
// stations.json is generated by scripts/build-stations.mjs from the Yandex
// `stations_list` method (~40 MB) and holds only Moscow-region railway stops
// as [yandexCode, title, direction] rows. It is Yandex data, so it is built
// at deploy time and not committed; without it only station codes resolve.
let STATIONS = [];
try {
  STATIONS = require("./stations.json");
} catch {
  // not built yet
}

const CODE_RE = /^s\d+$/;

const NOISE = new Set(["платформа", "пл", "станция", "ст", "оп", "о", "п"]);

// JS `\b` is ASCII-only, so words are split explicitly to drop "пл.", "ст." etc.
function normalize(name) {
  return String(name)
    .toLowerCase()
    .replace(/ё/g, "е")
    .split(/[^a-zа-я0-9]+/)
    .filter((w) => w && !NOISE.has(w))
    .join(" ");
}

// Returns {code, title, direction} or null.
// Order: explicit code, exact name, name prefix, substring.
function resolveStation(query, stations = STATIONS) {
  const q = String(query ?? "").trim();
  if (!q) return null;
  if (CODE_RE.test(q)) {
    const row = stations.find((s) => s[0] === q);
    return row ? toStation(row) : { code: q, title: q, direction: "" };
  }
  const n = normalize(q);
  const byName = stations.map((s) => [s, normalize(s[1])]);
  const pick =
    byName.find(([, t]) => t === n) ??
    byName.find(([, t]) => t.startsWith(n)) ??
    byName.find(([, t]) => t.includes(n));
  return pick ? toStation(pick[0]) : null;
}

function searchStations(query, limit = 10, stations = STATIONS) {
  const n = normalize(query);
  if (!n) return [];
  return stations
    .filter((s) => normalize(s[1]).includes(n))
    .slice(0, limit)
    .map(toStation);
}

function toStation([code, title, direction]) {
  return { code, title, direction };
}

module.exports = { normalize, resolveStation, searchStations };
